/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 mango-v1.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mango-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mango.geometry} material={materials.material_0} position={[0, 1.68, 0]} />
    </group>
  )
}

useGLTF.preload('/mango-v1-transformed.glb')
